### ISSUE TITLE
Conflicting dependencies in pitest classpath

### ISSUE THREAD

**Issue by stemas** [koral--/gradle-pitest-plugin#112]
**Describe the bug**
The classpath for Pitest should contain everything from the unitTestRuntimeClasspath (#95). Since 0.2.12 this is implemented for AGP > 4, but there is  a problem, if the compile classpath contains a different version of a dependency than the test classpath. E.g. 
```gradle
dependencies {
    implementation("org.jetbrains.kotlin:kotlin-reflect:1.6.10")
    testImplementation("io.mockk:mockk:1.11.0")
}
```
This creates a Pitest classpath which contains kotlin.reflect two times:
```text
.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-reflect/1.3.72/86613e1a669a701b0c660bfd2af4f82a7ae11fca/kotlin-reflect-1.3.72.jar
.gradle/caches/transforms-3/f86e6f0e014fe96a3034a99d2222bc0d/transformed/jetified-kotlin-reflect-1.6.10.jar
```
In this case 1.3.72 is used as it is the first one in the classpath which leads to runtime errors.

The problem is caused by the `copyRecursive` call which return the specified version of a dependency instead of the actually used version  : https://github.com/koral--/gradle-pitest-plugin/blob/master/src/main/groovy/pl/droidsonroids/gradle/pitest/PitestPlugin.groovy#L228

**Expected behavior**
The Pitest classpath should contain each dependency only once.

**Version used**
pl.droidsonroids.pitest 0.2.14

**Suggested Solution**
I'm wondering why the filtering with `copyRecursive` is necessary. If I remove it completely and just use `from(project.configurations["${variant.name}UnitTestRuntimeClasspath"])`, then the Pitest classpath contains all runtime dependencies only once and in the correct version. 
This change would also solve issues #99 and #100.

**Comment by koral--** [comment]
Thanks for the report. I'll look at that.
AFAIK the condition were added because without it there was an error `Cannot choose between the following variants of …` like e.g. this: https://youtrack.jetbrains.com/issue/KT-52966/Cannot-choose-between-the-following-variants-of-org.jetbrains.kotlinkotlin-gradle-plugin1.7.0

**Comment by stemas** [comment]
If copyRecursive is needed, then this should work:
```
 Configuration unittestRuntimeConfig = project.configurations.getByName("${variant.name}UnitTestRuntimeClasspath")
                from(unittestRuntimeConfig.copyRecursive { Dependency dependency ->
                    dependency.properties.dependencyProject == null && dependency.version != null
                }.shouldResolveConsistentlyWith(unittestRuntimeConfig))
```
