### ISSUE TITLE
Android classes from Android SDK in pitest classpath with compile compatibility set to `JavaVersion.VERSION_11`

### ISSUE THREAD

**Issue by Pfoerd** [koral--/gradle-pitest-plugin#116]
## Describe the bug
* Minimal Android App setup with gradle-pitest-plugin
* Set compile compatibility to JavaVersion.VERSION_11 like
```
android {
   compileOptions {
     sourceCompatibility = JavaVersion.VERSION_11
     targetCompatibility = JavaVersion.VERSION_11
   }
}
```
* disable mockable Android jar `excludeMockableAndroidJar.set(true)` because Android classes come into the project by using alternatives like UnMock or Robolectric
* Runninng pitest task results in errors because android.jar from Android SDK is added to the classpath of pitest and so the Android classes are loaded from there (instead of using the intended ones from e.g. UnMock or Robolectric, custom shadows etc.)

Root cause is that android.jar from Android SDK is always added to classpath when executing Pitest (can be seen in verbose output). This has no effect when excludeMockableAndroidJar is disabled as the mockable Android jar is always added at the top of the classpath and therefore "wins" classloading. But when excludeMockableAndroidJar is enabled it loads the Android classes from the android.jar instead of from alternative source like UnMock etc.

## Expected behavior
No android.jar is added to pitest classpath

## Version used
pl.droidsonroids.pitest 0.2.15

## Suggested Solution
It seems that this is a fix of the Android Gradle Plugin to fix issues with the Java module system introduces with Java 9 (see [this](https://issuetracker.google.com/issues/168044181#comment3) and [this](https://issuetracker.google.com/issues/139013660) issue in Android issue tracker).
So android.jar is probably added to classpath via [PitestPlugin#241](https://github.com/koral--/gradle-pitest-plugin/blob/master/src/main/groovy/pl/droidsonroids/gradle/pitest/PitestPlugin.groovy#L241) and [PitestPlugin#245](https://github.com/koral--/gradle-pitest-plugin/blob/master/src/main/groovy/pl/droidsonroids/gradle/pitest/PitestPlugin.groovy#L245), thus it seems android.jar is not added via a configuration but directly to the compileTask classpath. 

Thus, Android.jar should be somehow removed from the classpath.

**Comment by Pfoerd** [comment]
We built a local workaround by just removing the _android.jar_ from the `additionClasspath` of the pitest task

```private fun Project.configureAgpJava11Fix() {
    if (baseExtension.compileOptions.sourceCompatibility.isJava9Compatible &&
        baseExtension.compileOptions.targetCompatibility.isJava9Compatible &&
        pluginExtension.excludeMockableAndroidJar.getOrElse(false)
    ) {
        tasks.withType<PitestTask> {
            val classpathWithoutAndroidJar = additionalClasspath.filter { classpathEntry ->
                !(
                    classpathEntry.path.startsWith(project.extensions.getByType(BaseExtension::class.java).sdkDirectory.path) &&
                        classpathEntry.name == "android.jar"
                    )
            }
            additionalClasspath.setFrom(classpathWithoutAndroidJar)
        }
        logger.lifecycle("Removed android.jar from Pitest classpath to fix https://github.com/koral--/gradle-pitest-plugin/issues/116")
    }
}
``` 

If no other option exists maybe something like this could be a possible fix for this in the plugin itself?

**Comment by Pfoerd** [comment]
Hi @koral-- . Unfortunately it seems that your fix doesn't work on Windows because you hardcoded the file separator in the regex as forward-slash. Could you please provide a OS independent solution (maybe using File.separator or something like that)?

**Comment by koral--** [comment]
Ah I forgot about Windows :/
Sure, will fix it ASAP.
And I'll add a CI on Windows machines using Appveyor or something like that (this maybe not ASAP) to prevent such issues in the future.

**Comment by koral--** [comment]
Done, version 0.2.18 released.
I've added appveyor CI on Windows.
Some tests don't pass only on Windows e.g. https://github.com/koral--/gradle-pitest-plugin/pull/119#discussion_r1434103161 
So for now they are skipped there.

**Comment by Pfoerd** [comment]
Hi @koral-- I'm really sorry that I have to come around with this annoying issue again but with 0.2.17 I get the following exception:
```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':pitestDebug'.
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:38)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	...
Caused by: java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
\
	at java_lang_String$split.call(Unknown Source)
	at pl.droidsonroids.gradle.pitest.PitestPlugin$_configureTaskDefault_closure9$_closure23$_closure26.doCall(PitestPlugin.groovy:302)
	at jdk.internal.reflect.GeneratedMethodAccessor157.invoke(Unknown Source)
	...
```

It seems this is related to https://stackoverflow.com/questions/34129054/patternsyntaxexception-unexpected-internal-error-near-index-1-for-splitfile so I think this could be a solution: 
```
String splitter = File.separator.replace("\\","\\\\");
String[] split = abc.split(splitter);
```
(vgl. https://stackoverflow.com/a/34129096)

I think this should really be fixed as nobody will be able to use the plugin in on Windows machines if `excludeMockableAndroidJar` is enabled.

**Comment by koral--** [comment]
OK, thanks for the info. Will fix this ASAP.

**Comment by Pfoerd** [comment]
0.2.18 looks good on Windows. Thank's a lot for your effort!
