### ISSUE TITLE
After update project require SDK 21

### ISSUE THREAD

**Issue by emartynov** [koral--/gradle-pitest-plugin#140]
We tried to update and Gradle says that plugin requires JDK 21 for our project.

I quickly skimmed last changes and I believe it is target source compatibility removal.

Was it intentional?

**Comment by koral--** [comment]
Bumping the JDK version itself was intentional because Java 1.8 is not compatible with the recent AGP versions.
Maybe 17 will also work. I'll check that.

**Comment by veda-vitality** [comment]
I am using 17 but its not working.

**Comment by Pfoerd** [comment]
Would be great to go back to Java 17 as going to java 21 is a big step. E.g. we cannot use java 21 yet in our projects.

**Comment by koral--** [comment]
Could someone share a reproducer project demonstrating this issue on 0.2.19?
All the functional tests seem to pass on java 17.

**Comment by JasonLau13** [comment]
I was able to reproduce the error I saw by creating a project with empty activity and adding the pitest plugin. 

For NPE error, I have set `pl.droidsonroids.pitest` to '0.2.18`.

If you want to see the incompatibility error with JAVA 17, you can simply change the version to `0.2.19`

[TestAndroidProject.zip](https://github.com/user-attachments/files/17048031/TestAndroidProject.zip)

**Comment by koral--** [comment]
Thanks, will check on that project.

**Comment by emartynov** [comment]
You don't have a test project in this repo, correct? I believe it is just forcing specific JDK in the test project that is lower than 21.

**Comment by mp3killa** [comment]
+1

**Comment by jonas-ms** [comment]
@emartynov Can confirm your assumption: just tried checking out a local copy of this plugin and adding the following to its `build.gradle` file:

```groovy
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}
```

Everything seems to work as expected after this change.

**Comment by emartynov** [comment]
@jonas-ms thanks for the confirmation!

Do you mind to contribute your fork change here?

**Comment by jonas-ms** [comment]
> @jonas-ms thanks for the confirmation!
> 
> Do you mind to contribute your fork change here?

Sure, will do
