### ISSUE TITLE
Android Plugin 3.0.0 Support

### ISSUE THREAD

**Issue by cosminstirbu** [koral--/gradle-pitest-plugin#17]
Hello,

We're trying to migrate our project to use Android Studio 3.0 and we're receiving the following error:

```
Error:Could not find com.android.tools.build:gradle:3.0.0-rc1.
Searched in the following locations:
    file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/android/tools/build/gradle/3.0.0-rc1/gradle-3.0.0-rc1.pom
    file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/android/tools/build/gradle/3.0.0-rc1/gradle-3.0.0-rc1.jar
    https://maven.fabric.io/public/com/android/tools/build/gradle/3.0.0-rc1/gradle-3.0.0-rc1.pom
    https://maven.fabric.io/public/com/android/tools/build/gradle/3.0.0-rc1/gradle-3.0.0-rc1.jar
    https://plugins.gradle.org/m2/com/android/tools/build/gradle/3.0.0-rc1/gradle-3.0.0-rc1.pom
    https://plugins.gradle.org/m2/com/android/tools/build/gradle/3.0.0-rc1/gradle-3.0.0-rc1.jar
Required by:
    project :app > gradle.plugin.pl.droidsonroids.gradle:gradle-pitest-plugin:0.1.2
<a href="openFile:/Users/cosminstirbu/Documents/my-app/build.gradle">Open File</a>
```

These are our build.gradle snippets:

```
buildscript {
    ext.kotlin_version = '1.1.51'
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:3.0.0"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
```

and

```
buildscript {
    repositories {
        maven {
            url 'https://maven.fabric.io/public'
        }
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }

    dependencies {
        classpath 'io.fabric.tools:gradle:1.+'
        classpath 'gradle.plugin.pl.droidsonroids.gradle:gradle-pitest-plugin:0.1.2'
    }
}

plugins {
    id "pl.droidsonroids.pitest" version "0.1.2"
    id "io.gitlab.arturbosch.detekt" version "1.0.0.M12.1"
}
```

Any help is appreciated.

Thank you,
Cosmin

**Comment by koral--** [comment]
For Android Gradle plugin 3.0.0 or newer, you need to add Google maven repo to buildscript repositories. It is explained in migration guide: https://developer.android.com/studio/releases/gradle-plugin.html
In your case just add `google()`, so  that block will look like that:
```
buildscript {
    repositories {
        maven {
            url 'https://maven.fabric.io/public'
        }
        maven {
            url "https://plugins.gradle.org/m2/"
        }
        google()
    }
...
```
You can do it also inside `allprojects` stanza in root build.gradle.
A few additional notes:
* you need Gradle (wrapper) 4.1 or newer, check in `gradle/wrapper/gradle-wrapper.properties`
* you don't need to add pitest plugin as `classpath` dependency and Gradle plugin portal maven repo (`https://plugins.gradle.org/m2/`) if it is specified in `plugins` block

**Comment by cosminstirbu** [comment]
You're right, adding `google()` fixed the issue (and I've also removed the `classpath` dependency and relied only on the `plugins` block.

However, since there's a stable `com.android.tools.build:gradle:3.0.0` shouldn't we update the plugin to reference the stable as well, instead of the `rc`? 

Having a look at
https://github.com/koral--/gradle-pitest-plugin/blob/master/build.gradle it seems the plugin references the `rc`.

**Comment by koral--** [comment]
You are right.
At the time of the latest commit, there was no stable version yet.
I'll update it ASAP, and release next plugin version.

**Comment by cosminstirbu** [comment]
Thank you!
