### ISSUE TITLE
Change timeout constant?

### ISSUE THREAD

**Issue by bnvinay92** [koral--/gradle-pitest-plugin#19]
Pitest can take quite long to run, especially when mutations cause infinite loops. Is there a way to change the timeout constant?

**Comment by szpak** [comment]
Do you mean time per mutation before mark it as `TIMED_OUT`? If yes, you can use `timeoutFactor` and `timeoutConst` respectively (see the [PIT documentation](http://pitest.org/quickstart/commandline/) for details).

**Comment by bnvinay92** [comment]
I can set a `timeoutFactor` in the plugin configuration block but setting a `timeoutConst` or `timeoutConstant` gives me a `Could not set unknown property 'timeoutConst' for object of type info.solidsoft.gradle.pitest.PitestPluginExtension.`

pitest {
  pitestVersion = "1.2.4"
  targetClasses = [ 'com.olacabs.partner.android.*' ]
  outputFormats = ['HTML']
  threads = 9
  timestampedReports = false
  timeoutFactor = 1.2
  timeoutConstant = 40 // <-- error!
}

**Comment by bnvinay92** [comment]
Nvm, found it. `timeoutConstInMillis`

**Comment by szpak** [comment]
Right, I forgot that I changed the name in the Gradle plugin to make it more unambiguous long time ago :).
