### ISSUE TITLE
Android dependencies cause pitest to fail

### ISSUE THREAD

**Issue by manabreak** [koral--/gradle-pitest-plugin#20]
I tried running pitest on a test project with a single class and a single test. It works just fine, but if I add an Android dependency, it fails with `ClassDefNotFoundError`. It works fine when running the default JUnit tests.

[This repo](https://github.com/manabreak/pitest-android-error) contains the project. Any idea what's going on there? It seems that for some reason `unitTests.returnDefaultValues = true` does not affect pitest.

**Comment by koral--** [comment]
I need to update mockable Android jar path in plugin.
For now, as a workaround you can add snipeet like this to `app/build.gradle`:
```
buildscript {
    rootProject.buildscript.configurations.maybeCreate("pitestTestCompile")
    rootProject.buildscript.dependencies {
        pitestTestCompile files("build/generated/mockable-android-26.default-values.v3.jar")
    }
}
```

**Comment by bnvinay92** [comment]
This workaround does not work with AGP 3.0.

**Comment by koral--** [comment]
There is no need to use workarounds, since version 0.1.4 contains proper fix: https://github.com/koral--/gradle-pitest-plugin/releases/tag/v0.1.4
Please create a new issue if you encounter some errors.
