### ISSUE TITLE
Pre-mutation run fails for code using Android classes with gradle version 4.3 or newer

### ISSUE THREAD

**Issue by kevinlyles** [koral--/gradle-pitest-plugin#27]
I'm having my (otherwise passing) unit tests fail under the pre-mutation test with pitest when I use gradle 4.3 or newer.  I'm using Robolectric 3.7.1 with gradle-pitest-plugin 0.1.5.  Interestingly, the pitest run for the one package in my project that doesn't use any Android classes still works.

The errors I get all complain about integer/google_play_services_version not being set for my project (and it's not, but I'm not changing that when I switch gradle versions).  Here's the full log from one of the errors:

```
android.content.res.Resources$NotFoundException: <package name>:integer/google_p
10:03:46 PM PIT >> INFO : MINION : lay_services_version
	at org.robolectric.android.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:88)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:333)
	at org.robolectric.internal.SandboxTestRunner$2
10:03:46 PM PIT >> INFO : MINION : .evaluate(SandboxTestRunner.java:245)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunn
10:03:46 PM PIT >> INFO : MINION : er.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.
10:03:46 PM PIT >> INFO : MINION : evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.pitest.junit.adapter.CustomRunnerExecutor.run(CustomRunnerExecutor.ja
10:03:46 PM PIT >> INFO : MINION : va:42)
	at org.pitest.junit.adapter.AdaptedJUnitTestUnit.execute(AdaptedJUnitTestUnit.java:85)
	at org.pitest.coverage.execute.CoverageDecorator.execute(CoverageDecorator.java:50)
	at org.pitest.testapi.execute.containers.UnContainer.execute(UnContainer.ja
10:03:46 PM PIT >> INFO : MINION : va:32)
	at org.pitest.testapi.execute.Pitest.executeTests(Pitest.java:57)
	at org.pitest.testapi.execute.Pitest.run(Pitest.java:48)
	at org.pitest.coverage.execute.CoverageWorker.run(CoverageWorker.java:51)
	at org.pitest.coverage.execute.CoverageMinion.ma
10:03:46 PM PIT >> INFO : MINION : in(CoverageMinion.java:91)
```

It's possible this is actually a Robolectric issue, but I'm leaning towards it being a pitest one because Robolectric works just fine in normal unit test execution.

I discovered this because the newest version (3.1.0) of the gradle plugin for Android Studio requires gradle to be at least version 4.4.  However, the version I was using (3.0.1) also supports gradle 4.4, so I was able to test without changing anything but the gradle version.

I'm happy to try things out or get more information -- let me know what would be useful.  I can even try to whittle the project down to something small enough to attach -- I just want to know that this wasn't a known issue before putting that time in.

**Comment by koral--** [comment]
>  I can even try to whittle the project down to something small enough to attach 

That would be the best option IMHO. It will be much easier to investigate this with minimal  sample project which can reproduce this issue.

I recall issues with Robolectric & Android resources after Android Gradle plugin 3.0.0 was released e.g.: https://github.com/robolectric/robolectric/issues/3169#issuecomment-345792554
The solution was to add `includeAndroidResources = true`.

**Comment by kevinlyles** [comment]
Alright, I'll work on whittling things down.  It may be several days.

**Comment by kevinlyles** [comment]
I've (finally) tracked it down to a single setting.  If I remove this line from gradle.properties, the normal unit tests work, but pitest fails:
`android.enableAapt2=false`

That line is deprecated in newer versions of gradle (I get a warning about it), but apparently still does something.  Here's the warning:
```
WARNING: The option 'android.enableAapt2' is deprecated and should not be used anymore.
Use 'android.enableAapt2=true' to remove this warning.
It will be removed at the end of 2018..
```

Here's a reasonably-small project that shows the issue (it doesn't have the setting enabled):

[pitest-bug.zip](https://github.com/koral--/gradle-pitest-plugin/files/1913395/pitest-bug.zip)

**Comment by koral--** [comment]
Sorry for the delay, and thanks for the sample project. I'll investigate that.

**Comment by koral--** [comment]
For now workaround is to add snippet like this to root buildscript:

```gradle
    configurations.maybeCreate('pitestTestCompile')
    dependencies {
//...
        pitestTestCompile files('app/build/intermediates/unitTestConfig/test/debug/')
```

I need to implement proper fix in the plugin.

**Comment by kevinlyles** [comment]
It works!  Thank you for the warningless workaround!

To clarify for anyone else reading this: I added those lines to the buildscript section of the build.gradle for the project, then removed android.enableAapt2=false from gradle.properties.

Let me know if you'd like me to try out the fix when it's ready.

**Comment by koral--** [comment]
Fix is available in version `0.1.6-SNAPSHOT`. I've added classes from your attachment as a functional test.

**Comment by bnvinay92** [comment]
Where is `0.1.6-SNAPSHOT` hosted?

**Comment by koral--** [comment]
On the OSS snapshot repo.
If you are using Gradle add this to `repositories` block inside `buildscript`:
```
    maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
```
