### ISSUE TITLE
Publish the plugin v 0.0.5

### ISSUE THREAD

**Issue by xgouchet** [koral--/gradle-pitest-plugin#3]
The readme installation instruction mentions that the latest version is `0.0.5`, but on mavenCentral, the latest version is `0.0.4`. 

Could you publish the version 0.0.5 or change the readme ?

**Comment by koral--** [comment]
I forgot to upload archives to maven central. Will do it ASAP.

**Comment by IlyaEremin** [comment]
Not so asap 😏 still not uploaded

**Comment by koral--** [comment]
Sorry for the delay. Just released. It may take several hours to propagate to all maven central mirrors.
I've also updated the README.
