### ISSUE TITLE
Using plugin for java modules

### ISSUE THREAD

**Issue by lachudra87** [koral--/gradle-pitest-plugin#42]
Is it possible to use this version of plugin (android fork) also for pure java project? I have some java submodules in application and couldn't manage to use android plugin there. And also cannot use original version as it has same package and cannot use both versions at same time.

**Comment by szpak** [comment]
Not really in the current form. There are (among others) different type of base tasks in the pure Java and the Android projects and (as the author of the original plugin) I had seen it problematic (in a case of code readability and maintainability) to maintain both variants in the same code base. An (occasionally synchronized) fork seems to work fine in most cases.

The same package name for classes can be problematic. I don't know how the class loaders are configured in Gradle internals, but have you tried to apply the Java plugin only for Java modules and the Android plugin for Android modules?
In a case it fails you could - as a workaround - have a PIT execution for Android by default and an execution for Java conditionally triggered (e.g. with `-PwithPitForJava`) when the Android Pit plugin is not loaded/applied at all.

**Comment by koral--** [comment]
Thanks for the report. I'll check this case.
I think renaming those conflicting class names in this fork is not a problem.

**Comment by szpak** [comment]
They will be tree conflicts on merging the upstream changes (such as support for 1.4.x features which hopefully will occur that year), however, it's just a few files, to it might not be a (very) big problem.

Anyway, @lachudra87 , have you checked the workarounds I proposed?

**Comment by lachudra87** [comment]
Finally we applied android plugin for all modules, but there are some plans for new java modules so any fix would be appreciated.
