### ISSUE TITLE
Support for UnMock Gradle Plugin

### ISSUE THREAD

**Issue by xsveda** [koral--/gradle-pitest-plugin#49]
When a test calls some class from Android API, one need to mock it first (or use default values).
But some utility or data classes (i.e. `android.net.Uri`) from `android.jar` don't need to be mocked but instead may be "un-mocked" by copying their real implementation from real `android.jar`.

There is a [UnMock Gradle Plugin](https://github.com/bjoernQ/unmock-plugin) that does exactly that.

I'm not familiar with the internals of Pitest plugin but do you see any chance that Pitest may call unMock task before running the tests so we don't need to mock Android APIs?

**Comment by koral--** [comment]
It seems to be doable.
I think the only thing we need to add to pitest plugin is an option to not add mockable Android JAR to classpath. In such case JAR generated by UnMock will be used automatically (that plugin adds task generating it as a dependency).

**Comment by koral--** [comment]
Feature added in version 0.2.1
You have to add `excludeMockableAndroidJar = true` to pitest configuration.
