### ISSUE TITLE
Apply upstream change for pitest minion classpaths

### ISSUE THREAD

**Issue by davidburstromspotify** [koral--/gradle-pitest-plugin#53]
The following upstream change is required on large Android projects. Could this be cherry-picked (and released)? This is afaik the last thing required to stop us from using an internal fork of the plugin. Thank you!

https://github.com/szpak/gradle-pitest-plugin/commit/6659a304d3840f94bd54f89e936c72dacef11a1c

**Comment by szpak** [comment]
@davidburstromspotify It's in the devel branch right now. I plan to release 1.4.6 with that change this week.
