### ISSUE TITLE
Failed on relaxed mocks

### ISSUE THREAD

**Issue by BulatMukhutdin** [koral--/gradle-pitest-plugin#57]
I am using [Mockk](https://mockk.io/) lib for mocks. It has properties that allow not to mock every mock's answer.  Using ```settings.properties```.
When I run tests the suite is green. But pitest fails saying that it isn't.
Here is the sample [project](https://github.com/BulatMukhutdin/pitest-coroutines)

Do you have any idea how to force pitest take into consideration given mockk's properties?

**Comment by koral--** [comment]
Thanks for the report I'll check this.

**Comment by BulatMukhutdin** [comment]
@koral-- any updates on this?

**Comment by koral--** [comment]
Sorry, not yet. I'll try to investigate it tomorrow.

**Comment by koral--** [comment]
Sorry for the late reply again.
It seems that location of processed resources (`settings.properties` in this case) has changed since AGP 3.6 so it is not taken into account when running pitest.
This issue should be fixed in version 0.2.3-SNAPSHOT.

**Comment by BulatMukhutdin** [comment]
Happy to hear that. Could you give me an idea when this version would be available to use?

**Comment by koral--** [comment]
You can use snapshot version after adding maven snapshot repo to a buildscript.
I'm now working on integrating changes from upstream (parent repo) and I'm planning to release those along with fix for this issue. I'll try to finish on this weekend but can't promise exact ETA.

**Comment by szpak** [comment]
@koral-- FYI. I've just pushed some new changes to master. You might want to take it into account or wait when the new release - with some other changes - is ready (probably a few days).
