### ISSUE TITLE
Configuration with name 'debugCompileClasspathCopy' not found.

### ISSUE THREAD

**Issue by shivaburugu** [koral--/gradle-pitest-plugin#64]
unable to run pitest with gradle version 4.0.0 on android projects, getting below error when running task pitest

> Task :app:pitestDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:pitestDebug'.
> Configuration with name 'debugCompileClasspathCopy' not found.

**Comment by scardonau** [comment]
Same issue for me

**Comment by JavaAdam** [comment]
Same issue for me with com.android.tools.build:gradle:4.0.1

**Comment by koral--** [comment]
Fix is available in version 0.2.5-SNAPSHOT.

**Comment by peterbetos** [comment]
Was 0.2.5-SNAPSHOT released?

**Comment by koral--** [comment]
Yes, it's in the snapshot repository:
https://oss.sonatype.org/content/repositories/snapshots/pl/droidsonroids/gradle/gradle-pitest-plugin/0.2.5-SNAPSHOT/
You need to add `https://oss.sonatype.org/content/repositories/snapshots` to your maven/gradle repositories.
