### ISSUE TITLE
Version 0.2.4 cannot resolve all artifacts

### ISSUE THREAD

**Issue by ppoetz** [koral--/gradle-pitest-plugin#66]
Hey,
Thanks for providing this plugin. I somehow can't get it to run.

When I try to run `gradlew pitest` with version `0.2.2` I get the following error:
`The value for task ':app:pitestDebug' property 'mainClass' is final and cannot be changed any further.`

Then I saw you've already released a fix for this in `0.2.4`.
But this version cannot be fully resolved:

```
A problem occurred configuring root project 'your.training'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find pl.droidsonroids.gradle:gradle-pitest-plugin:0.2.4.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/pl/droidsonroids/gradle/gradle-pitest-plugin/0.2.4/gradle-pitest-plugin-0.2.4.pom
       - https://dl.google.com/dl/android/maven2/pl/droidsonroids/gradle/gradle-pitest-plugin/0.2.4/gradle-pitest-plugin-0.2.4.pom
       - https://jcenter.bintray.com/pl/droidsonroids/gradle/gradle-pitest-plugin/0.2.4/gradle-pitest-plugin-0.2.4.pom
```

Quite a dilemma. Can you help me out?

This is a part of my `build.gradle` file:

```
buildscript {
    ext.kotlin_version = '1.3.72'

    repositories {
        mavenCentral()
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.6.4'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'pl.droidsonroids.gradle:gradle-pitest-plugin:0.2.4'
    }
}
```

EDIT:
Ok, I found out a little bit more.
When looking here: https://repo.maven.apache.org/maven2/pl/droidsonroids/gradle/gradle-pitest-plugin/
I can see that the last published version is 0.2.2. 
Would you kindly upload the artifacts for 0.2.4 to the maven central repository?

**Comment by koral--** [comment]
Indeed version 0.2.4 is not visible on maven central. I'll try to fix it ASAP.

**Comment by koral--** [comment]
In the meantime, workaround is to use gradle plugin portal: https://plugins.gradle.org/plugin/pl.droidsonroids.pitest
or maven central snapshot repos.

**Comment by ppoetz** [comment]
Thank you very much!
I workarounded it by using gradle 6.3 and pradle-pitest-plugin:0.2.2

**Comment by koral--** [comment]
0.2.4 has been published and should be available within few hours.
