### ISSUE TITLE
Sync with root repo to enable skipFailingTests parameter

### ISSUE THREAD

**Issue by afaucogney** [koral--/gradle-pitest-plugin#69]
I tried to use pitest on a huge project, and some test cases went to trouble. On original PIT, there is the option skipFailingTests that enable skipping test with pb.

https://github.com/szpak/gradle-pitest-plugin/search?q=skipFailingTests&unscoped_q=skipFailingTests

Do you plan sync soon ? ( I hope repos didn't diverged)

**Comment by koral--** [comment]
It is available in v0.2.5-SNAPSHOT.
I'll try to release v0.2.5 it today.

**Comment by koral--** [comment]
Done, 0.2.5 should be available on maven central up to 2 hours.
