### ISSUE TITLE
Merge Report Aggregator Plugin

### ISSUE THREAD

**Issue by Pfoerd** [koral--/gradle-pitest-plugin#79]
First of all: i really appreciate your work on the android fork of gradle-pitest-plugin, it enables us to use mutation testing in our large-scale android setups 😄 .

Could you please merge the "new" [PitestAggregatorPlugin ](https://gradle-pitest-plugin.solidsoft.info/#multi-module-projects-support) to improve support of Multi-module project setups?
It can't be used without modifications because it forces subprojects to have a plugin with id "info.solidsoft.pitest" applied and uses it's extension type.

**Comment by Pfoerd** [comment]
Thanks a lot! :)

**Comment by Pfoerd** [comment]
@koral-- did you test the Aggregator Plugin? I get a NPE for the charset as it is not set. After exploring the code I think you have to set a charset [here](https://github.com/koral--/gradle-pitest-plugin/blob/master/src/main/groovy/pl/droidsonroids/gradle/pitest/AggregateReportGenerator.groovy#L26) to get it work? 

It seems that the DirectorySourceLocator mandatory needs it [here](https://github.com/hcoles/pitest/blob/58c9744a06df92cbbbf36c9f3376a1175d61f8ad/pitest-entry/src/main/java/org/pitest/mutationtest/tooling/DirectorySourceLocator.java#L49) to read the xml files?

**Comment by Pfoerd** [comment]
I'm using latest pitest Release 1.9.2, maybe its an incompatibility?

**Comment by Pfoerd** [comment]
@koral-- After looking a bit deeper into this I think I was introduces with 1.8.1 of pitest release about one month ago (see [this](https://github.com/hcoles/pitest/pull/1029/files#diff-c60171bb93f23380072c03a64028e4526c59e8ea63555f94069c22ca65dc5ecaR47)change

**Comment by szpak** [comment]
> @koral-- After looking a bit deeper into this I think this incompatibility was introduces with 1.8.1 of pitest release about one month ago (see [this](https://github.com/hcoles/pitest/pull/1029/files#diff-c60171bb93f23380072c03a64028e4526c59e8ea63555f94069c22ca65dc5ecaR47) change)

Good catch @Pfoerd.

@hcoles, passing the charset will be added in the next version of the plugin, but I wonder, if `ReportAggregator` (being somehow a public API), for backward compatibility, couldn't set a default value by default, as it is already done in `ConfigOption`?

**Comment by hcoles** [comment]
@szpak I'll add some defaults in for the next release.

**Comment by Pfoerd** [comment]
This is fixed in [Pitest 1.9.3](https://github.com/hcoles/pitest/releases/tag/1.9.3), thanks @hcoles

**Comment by koral--** [comment]
Thanks for the updates.
I assume that I can close this issue then.
