### ISSUE TITLE
Cannot resolve external dependency org.pitest:pitest-command-line:1.1.11

### ISSUE THREAD

**Issue by xklakoux** [koral--/gradle-pitest-plugin#8]
Hi there,
I'm trying to use plugin in my android project, but without any luck.
Gradle syncs fine but what I'm getting when running any pitest gradle task is this:
```
Could not resolve all dependencies for configuration ':pitest'.
> Cannot resolve external dependency org.pitest:pitest-command-line:1.1.11 because no repositories are defined.
  Required by:
      project :
```

I've added the classpath
```
buildscript {
    ext.kotlin_version = '1.1.2-3'
    repositories {
        mavenCentral()
        ...
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'
        ...
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'pl.droidsonroids.gradle:gradle-pitest-plugin:0.0.8'
    }
}
```
and plugin 
`apply plugin: "pl.droidsonroids.pitest"`

[stacktrace](https://pastebin.com/raw/yJP5mmbR)

I'm using:
android studio 2.3.3 
kotlin 1.1.2
gradle version 3.5
gradle plugin 2.3.3

I realize there might be something unusual in my project that make it fail, but I'd appreciate any insight. Thanks!

**Comment by szpak** [comment]
@xklakoux Could you confirm that the mentioned `buildscript` section is placed in the root Gradle project (which is required by the PIT plugin)?

**Comment by xklakoux** [comment]
Well, I can confirm that I started getting results when I put that in there. Sorry to bother you with such silly mistake. Thanks again.

**Comment by szpak** [comment]
No problem. You are not the [only one](https://github.com/szpak/gradle-pitest-plugin/issues/62). I plan to change it in the future.
