### ISSUE TITLE
Cannot resolve external dependency org.pitest:pitest-command-line:1.7.0

### ISSUE THREAD

**Issue by rameshphilips** [koral--/gradle-pitest-plugin#83]
>  What went wrong:
>  Execution failed for task ':app:pitestAzulReleaseWithLogs'.
>  Could not resolve all files for configuration ':app:pitest'.
>     Cannot resolve external dependency org.pitest:pitest-command-line:1.7.0 because no repositories are defined.
>       Required by:
>           project :app

Getting the above error.

pitest.gradle task like below 

> apply plugin: 'pl.droidsonroids.pitest'
> 
> pitest {
>     threads = Runtime.getRuntime().availableProcessors()
>     mutationThreshold = 80 // percent perform at pass
>     failWhenNoMutations = false
>     verbose = false // Enable/disable execution logging
>     jvmArgs = ['-Xmx1024m']
>     outputFormats = ['XML', 'HTML']
>     targetClasses = ['com.company.queuemanager.*']
>     excludeMockableAndroidJar = true
> }

Root build.gradle

classpath "pl.droidsonroids.gradle:gradle-pitest-plugin:0.2.9"

using the pitest.gradle task I have applied for a subproject. For now at 'app' module throwing this error. any idea where I am doing wrong here.

Thank you

**Comment by koral--** [comment]
It seems that you have no repositories defined.
You should have something like:
```
  repositories {
    mavenCentral()
    google()
  }
```
in the `buildscript` block.

**Comment by szpak** [comment]
> classpath "pl.droidsonroids.gradle:gradle-pitest-plugin:0.2.9"

You seem to use the old syntax for plugins which might require some extra work with dependencies.. You could try to use the ["new" syntax](https://plugins.gradle.org/plugin/pl.droidsonroids.pitest):

```
plugins {
  id "pl.droidsonroids.pitest" version "0.2.9"
}
```

(anyway, `repositories { ... }` in the `build.gradle` in the module you apply the plugin might be needed for pitest dependencies which are added at "runtime")

**Comment by rameshphilips** [comment]
Thank you koral-- and szpak
