### ISSUE TITLE
Error running any pitest with Kotlin version 1.7.10

### ISSUE THREAD

**Issue by im-not-josh** [koral--/gradle-pitest-plugin#84]
I see the following error when I run any pitest task with Kotlin version 1.7.10
Could not determine the dependencies of task ':projectname:pitestDebug'.
> Could not get unknown property 'destinationDir' for task ':projectname:compileDebugKotlin' of type org.jetbrains.kotlin.gradle.tasks.KotlinCompile.

Reverting back to kotlin 1.6.21 fixes the issue.

This issue may be related to pittest itself, rather than this plugin

**Comment by miguelmanzo** [comment]
Same  issue over here 🙏

**Comment by maxtracking** [comment]
Well, you could fix it by replacing that `destinationDir` property by `destinationDirectory.asFile` if I remember correctly

**Comment by im-not-josh** [comment]
Do you know where that property is/how to set it? I didn't look terribly
hard but it wasn't immediately clear to me how to do that

Thanks.
Josh.
