### ISSUE TITLE
Reports are not written to variant specific directories

### ISSUE THREAD

**Issue by Pfoerd** [koral--/gradle-pitest-plugin#87]
**Describe the bug**
When running variant specific tasks of pitest (`pitestDebug` and `pitestRelease`) all reports are written to the same directory and overwrite each other. The [documentation](https://github.com/koral--/gradle-pitest-plugin#usage) describes a different behavior.

**To Reproduce**
1. Create an empty Android project generated with Android Studio
2. Configure gradle-pitest-plugin
3. ``` pitest {
    targetClasses = ['de.foo.*']
    pitestVersion = "1.9.8"
4. run `pitestDebug`
5. run `pitestRelease`

**Expected behavior**
The reports are written to:
* `build/reports/pitest/pitestDebug` for Debug variant
* `build/reports/pitest/pitestRelease` for Release variant

like described in the [Readme](https://github.com/koral--/gradle-pitest-plugin#usage).

**used version:**
2.9.0 and 2.10.0

**Comment by koral--** [comment]
Thanks for the report, will check that.
